### PR TITLE
chore: the io/ioutil package is deprecated from Go 1.16

### PR DESCRIPTION
**Pull request by jenting**
### Propose Changes
- The `io/ioutil` package is deprecated.
- Update the base Go version from 1.13 to 1.17.

### CODE REVIEW

**Review by innobead — CHANGES_REQUESTED** [review]
Let's update go version to 1.17 to align with all components and libs.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@jenting Please help update the dependencies of the dependent components in the master and 1.4.x branches. They should be longhorn-engine and backing-image-manager. 

cc @longhorn/dev-data-plane

**Comment by jenting** [comment]
> @jenting Please help update the dependencies of the dependent components in the master and 1.4.x branches. They should be longhorn-engine and backing-image-manager.
> 
> cc @longhorn/dev-data-plane

@innobead There is the dependabot configuration triggered every week in longhorn-engine and backing-image-manager. Shouldn't we rely on the bot to update the dependency?

**Comment by innobead** [comment]
@jenting Sounds good, but unfortunately, this is quite different from external dependencies, since the change of our shared libraries would immediately impact the functional integration. However, the idea is good and reasonable for sure.

**Pull request merged**
